const evenements = [
    {
        "id": 0,
        "type": "TD",
        "date": "12-12-2024",
        "heure": "08:00",
        "duree_h": 1.5,
        "module": "INFO731",
        "enseignant": "KV",
        "salle": "C111",
        "groupes": ["IDU4", "SNI4"],
        "couleur": "#FF0000"
    },
    {
        "id": 1,
        "type": "CM",
        "date": "13-12-2024",
        "heure": "10:00",
        "duree_h": 1.5,
        "module": "INFO731",
        "enseignant": "KV",
        "salle": "C111",
        "groupes": ["IDU4", "SNI4"],
        "couleur": "#FF0000"
    },
    {
        "id": 2,
        "type": "TD",
        "date": "13-12-2024",
        "heure": "13:00",
        "duree_h": 2.5,
        "module": "INFO732",
        "enseignant": "KV",
        "salle": "C110",
        "groupes": ["IDU4"],
        "couleur": "#00FF00"
    },
    {
        "id": 3,
        "type": "CM",
        "date": "16-12-2024",
        "heure": "15:00",
        "duree_h": 2,
        "module": "INFO733",
        "enseignant": "Sorana",
        "salle": "A203",
        "groupes": ["IDU4", "SNI4"],
        "couleur": "#FF0000"
    },
    {
        "id": 4,
        "type": "TD",
        "date": "16-12-2024",
        "heure": "08:00",
        "duree_h": 3.3,
        "module": "MATH741",
        "enseignant": "AB.",
        "salle": "A203",
        "groupes": ["IDU4"],
        "couleur": "#0000FF"
    },
    {
        "id": 5,
        "type": "CM",
        "date": "16-01-2025",
        "heure": "10:00",
        "duree_h": 2,
        "module": "INFO731",
        "enseignant": "KV",
        "salle": "C111",
        "groupes": ["IDU4", "SNI4"],
        "couleur": "#FF0000"
    },
    {
        "id": 6,
        "type": "Projet",
        "date": "07-01-2025",
        "heure": "08:00",
        "duree_h": 4,
        "module": "PROJ731",
        "enseignant": "Flavien Vernier",
        "salle": "C202",
        "groupes": ["IDU4"],
        "couleur": "#00FF00"
    },
    {
        "id": 6,
        "type": "Projet",
        "date": "07-01-2025",
        "heure": "13:15",
        "duree_h": 4,
        "module": "INFO734",
        "enseignant": "Mian Ammar",
        "salle": "C209",
        "groupes": ["IDU4"],
        "couleur": "#00FFFF"
    },
    {
        "id": 7,
        "type": "Examen",
        "date": "08-01-2025",
        "heure": "10:00",
        "duree_h": 1.5,
        "module": "DATA732",
        "enseignant": "Cimpan Sorana",
        "salle": "C109",
        "groupes": ["IDU4"],
        "couleur": "#FFFF00"
    },
    {
        "id": 8,
        "type": "CM",
        "date": "09-01-2025",
        "heure": "08:15",
        "duree_h": 1.5,
        "module": "INFO734",
        "enseignant": "Mian Ammar",
        "salle": "C217",
        "groupes": ["IDU4"],
        "couleur": "#00FFFF"
    },
    {
        "id": 9,
        "type": "CM",
        "date": "09-01-2025",
        "heure": "10:00",
        "duree_h": 1.5,
        "module": "INFO734",
        "enseignant": "Mian Ammar",
        "salle": "C217",
        "groupes": ["IDU4"],
        "couleur": "#00FFFF"
    },
    {
        "id": 10,
        "type": "Examen",
        "date": "09-01-2025",
        "heure": "13:30",
        "duree_h": 1.5,
        "module": "MATH741",
        "enseignant": "Alexandre Bascop",
        "salle": "B120",
        "groupes": ["IDU4", "SNI4"],
        "couleur": "#FF0000"
    },
    ,
    {
        "id": 11,
        "type": "Examen - Tiers-temps",
        "date": "09-01-2025",
        "heure": "15:00",
        "duree_h": 0.5,
        "module": "MATH741",
        "enseignant": "Alexandre Bascop",
        "salle": "B120",
        "groupes": ["IDU4", "SNI4"],
        "couleur": "#FF0000"
    },
    {
        "id": 12,
        "type": "Autre",
        "date": "09-01-2025",
        "heure": "15:45",
        "duree_h": 1.5,
        "module": "EEE",
        "enseignant": "Alexandre Benoit",
        "salle": "C209, C210",
        "groupes": ["IDU4"],
        "couleur": "#333333"
    },
    {
        "id": 13,
        "type": "Projet",
        "date": "10-01-2025",
        "heure": "08:00",
        "duree_h": 4,
        "module": "PROJ731",
        "enseignant": "Flavien Vernier",
        "salle": "C214",
        "groupes": ["IDU4"],
        "couleur": "#00FF00"
    },
    {
        "id": 14,
        "type": "Projet",
        "date": "10-01-2025",
        "heure": "13:30",
        "duree_h": 4,
        "module": "PROJ731",
        "enseignant": "Flavien Vernier",
        "salle": "C215",
        "groupes": ["IDU4"],
        "couleur": "#00FF00"
    },
    {
        "id": 15,
        "type": "Projet",
        "date": "06-01-2025",
        "heure": "08:00",
        "duree_h": 4,
        "module": "ISOC731",
        "enseignant": "Kave Salamatian",
        "salle": "C215",
        "groupes": ["IDU4"],
        "couleur": "#0FFFF0"
    }
];

export default evenements;
