
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `APC_apprentissage_critique` WRITE;
/*!40000 ALTER TABLE `APC_apprentissage_critique` DISABLE KEYS */;
INSERT INTO `APC_apprentissage_critique` VALUES (1,1,'Concevoir, gérer et utiliser une base de données (INFO502 BD, APP : PROJ531)');
INSERT INTO `APC_apprentissage_critique` VALUES (2,1,'Concevoir et implémenter une application orientée objet de petite taille (<10classes) (INFO641)');
INSERT INTO `APC_apprentissage_critique` VALUES (3,1,'Résoudre un problème en implémentant un algorithme dans un programme informatique (INFO501)');
INSERT INTO `APC_apprentissage_critique` VALUES (4,1,'Mettre en œuvre une architecture client-serveur 3-tiers (INFO632 OS+Virtu)');
INSERT INTO `APC_apprentissage_critique` VALUES (5,1,'Concevoir et implémenter une application web de rendu de données / intégrant une BD (INFO633 Web+BD) ');
INSERT INTO `APC_apprentissage_critique` VALUES (7,2,'Définir les caractéristiques techniques et fonctionnelles d\'un système N-tiers (INFO833, INFO734_IDU)');
INSERT INTO `APC_apprentissage_critique` VALUES (8,2,'Spécifier et concevoir un logiciel (INFO732)');
INSERT INTO `APC_apprentissage_critique` VALUES (9,2,'Intégrer la dimension qualité et intégration continue dans le développement logiciel (INFO832)');
INSERT INTO `APC_apprentissage_critique` VALUES (10,2,'Choisir une méthode de développement adaptée (INFO734)');
INSERT INTO `APC_apprentissage_critique` VALUES (13,3,'Définir et mettre en œuvre une architecture de système logiciel de donnée massives(DATA831)\r\n');
INSERT INTO `APC_apprentissage_critique` VALUES (14,3,'Caractériser et choisir les solutions logicielles et systèmes adaptées aux besoins (INFO932)');
INSERT INTO `APC_apprentissage_critique` VALUES (15,3,'S\'assurer de la sûreté, la fiabilité et la sécurité du système, du traitement et des données (INFO731)');
INSERT INTO `APC_apprentissage_critique` VALUES (16,3,'Concevoir des applications et architectures multitâches et distribuées (INFO833)');
INSERT INTO `APC_apprentissage_critique` VALUES (17,3,'Évaluer et optimiser les performances opérationnelles et énergétiques d\'un système logiciel');
INSERT INTO `APC_apprentissage_critique` VALUES (34,4,'Acquérir des données provenant d’Internet (APP : PROJ531)');
INSERT INTO `APC_apprentissage_critique` VALUES (35,4,'Récupérer des données provenant d’un dépôt de données structurées (INFO502, INFO633)');
INSERT INTO `APC_apprentissage_critique` VALUES (36,4,'Organiser des données selon des structures de graphe  (MATH531 , PROJ631)');
INSERT INTO `APC_apprentissage_critique` VALUES (37,4,'Mobiliser des outils mathématiques (MATH500, MATH501, MATH641)');
INSERT INTO `APC_apprentissage_critique` VALUES (38,4,'Déployer les bases de la logique et de l’IA (INFO631)');
INSERT INTO `APC_apprentissage_critique` VALUES (39,4,'Visualiser les données (INFO633)');
INSERT INTO `APC_apprentissage_critique` VALUES (40,5,'Évaluer la qualité de la donnée (INFO832)');
INSERT INTO `APC_apprentissage_critique` VALUES (41,5,'Répartir les fonctionnalités (acquisition, stockage, traitements, visualisation...) sur un système N-Tieris (INFO834)');
INSERT INTO `APC_apprentissage_critique` VALUES (42,5,'Déployer des traitements distribués (INFO743, INFO731)');
INSERT INTO `APC_apprentissage_critique` VALUES (43,5,'Mobiliser des outils stochastiques (DATA731, MATH741)');
INSERT INTO `APC_apprentissage_critique` VALUES (44,5,'Développer des rendus visuels divers, en vue d’une aide à la décision (DATA732, INFO734, INFO831)');
INSERT INTO `APC_apprentissage_critique` VALUES (45,5,'Déployer des outils d’IA (DATA832, DATA931)');
INSERT INTO `APC_apprentissage_critique` VALUES (46,5,'Concevoir et mettre en œuvre une base de données NoSQL (INFO834)');
INSERT INTO `APC_apprentissage_critique` VALUES (47,6,'Mettre en œuvre des traitements big data (cloud, batch, flux..) (DATA831, INFO932, PROJ832)');
INSERT INTO `APC_apprentissage_critique` VALUES (48,6,'Développer des traitements distribués (INFO833, INFO932)');
INSERT INTO `APC_apprentissage_critique` VALUES (49,6,'Développer des rendus visuels divers, en vue d’une aide à la décision multi-critères (INFO931)');
INSERT INTO `APC_apprentissage_critique` VALUES (50,6,'Intégrer des solutions issues de la recherche (ISOC931, PROJ901)');
INSERT INTO `APC_apprentissage_critique` VALUES (51,6,'Caractériser et choisir une représentation de données et les traitements adaptés dans un contexte de big data (INFO834)');
INSERT INTO `APC_apprentissage_critique` VALUES (52,7,'Lier des problématique techniques au problématique societales (ISOC 531)');
INSERT INTO `APC_apprentissage_critique` VALUES (53,7,'Construire des API de Plateformes numériques (ISOC 631)');
INSERT INTO `APC_apprentissage_critique` VALUES (54,7,'Prendre en compte l’importance stratégique de la donnée (ISOC 631)');
INSERT INTO `APC_apprentissage_critique` VALUES (55,7,'Intégrer à la démarche d’ingénierie la dimension étique et de développement durable (ISOC 531, ISOC 631, DDRS501)');
INSERT INTO `APC_apprentissage_critique` VALUES (56,8,'Intégrer le cadre légal et réglementaire du traitement de données  (ISOC 731)');
INSERT INTO `APC_apprentissage_critique` VALUES (57,8,'Analyser et maîtriser les exigences du RGPD et du droit de la propriété (ISOC 731, INFO731)');
INSERT INTO `APC_apprentissage_critique` VALUES (58,8,'Intégrer les dimension économie de la donnée (valeur de la données, utilisation par les entreprise du numerique, mise en place business plan) (ISOC731)');
INSERT INTO `APC_apprentissage_critique` VALUES (59,9,'Identifier les risques de sécurité informatique sur les système et les données (fuite de données) (INFO731, PROJ931)');
INSERT INTO `APC_apprentissage_critique` VALUES (60,9,'Mettre en place les élément de sécurité et de cryptographie (INFO731, PROJ931)');
INSERT INTO `APC_apprentissage_critique` VALUES (61,9,'Intégrer l’intermédiation dans la conception des système numérique (INFO731, PROJ931)');
INSERT INTO `APC_apprentissage_critique` VALUES (62,9,'Comprendre les effets réseaux dans le développement des plateforme numérique (ISOC631)');
INSERT INTO `APC_apprentissage_critique` VALUES (63,9,'Expliquer les flux, stockage, sécurisation de la données au sein des entreprises (PROJ931)');
INSERT INTO `APC_apprentissage_critique` VALUES (64,10,'Définir  un projet, ses objectifs, ses acteur et les outils de gestion de projet (PROJ531)');
INSERT INTO `APC_apprentissage_critique` VALUES (65,10,'Mettre en œuvre une méthode de gestion de projet informatique et des outils collaboratifs associés (PROJ531)');
INSERT INTO `APC_apprentissage_critique` VALUES (66,10,'Mettre en œuvre des outils de planification et de suivi de projet  (PROJ531)');
INSERT INTO `APC_apprentissage_critique` VALUES (67,10,'Évaluer la rentabilité des projets (SHES601)');
INSERT INTO `APC_apprentissage_critique` VALUES (68,10,'Concevoir les bases d\'une stratégie d\'entreprise (SHES505)');
INSERT INTO `APC_apprentissage_critique` VALUES (69,10,'Comprendre les lois et réglementations qui régissent leur domaine d\'expertise (SHES602)');
INSERT INTO `APC_apprentissage_critique` VALUES (70,11,'Analyser les besoins, identifier les contraintes et élaborer un cahier des charges (INFO731)');
INSERT INTO `APC_apprentissage_critique` VALUES (71,11,'Animer les réunions et organiser le travail pour clarifier les attendus (SHES703)');
INSERT INTO `APC_apprentissage_critique` VALUES (72,11,'Identifier et évaluer les risques triviaux d\'un projet (SHES802)');
INSERT INTO `APC_apprentissage_critique` VALUES (73,11,'Utiliser les techniques de créativité pour apporter des solutions originales (SHES704)');
INSERT INTO `APC_apprentissage_critique` VALUES (74,11,'Analyser et évaluer les structures et les processus organisationnels (SHES803)');
INSERT INTO `APC_apprentissage_critique` VALUES (75,11,'Communiquer avec différentes cultures LANGXXX');
INSERT INTO `APC_apprentissage_critique` VALUES (76,12,'Utiliser des méthodes de management pour la motivation en projet (SHES 901)');
INSERT INTO `APC_apprentissage_critique` VALUES (77,12,'Manager des équipes projet (gestion des organisations, résistance au changement…) (SHES803, SHES901)');
INSERT INTO `APC_apprentissage_critique` VALUES (78,12,'Évaluer l\'impact du projet en interne et en externe (responsabilité sociétale et environnementale, stratégie de l\'entreprise…) (DDRS ???, SHES802)');
/*!40000 ALTER TABLE `APC_apprentissage_critique` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `APC_apprentissage_critique_as_module` WRITE;
/*!40000 ALTER TABLE `APC_apprentissage_critique_as_module` DISABLE KEYS */;
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (1,13,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (1,43,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (2,14,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (2,49,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (3,12,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (3,49,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (3,83,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (4,46,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (5,74,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (7,55,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (7,62,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (8,52,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (9,61,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (10,55,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (13,57,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (14,66,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (15,51,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (16,62,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (17,62,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (34,48,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (35,13,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (35,74,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (36,45,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (36,49,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (37,45,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (37,49,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (37,83,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (37,91,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (38,44,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (39,74,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (40,61,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (41,63,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (42,16,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (42,51,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (43,50,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (43,58,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (43,68,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (43,98,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (44,54,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (44,55,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (44,59,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (46,63,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (47,57,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (47,66,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (47,180,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (48,62,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (48,66,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (49,65,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (50,69,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (50,115,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (51,63,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (52,42,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (53,47,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (54,47,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (55,42,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (55,47,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (56,51,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (56,56,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (57,51,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (57,61,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (58,42,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (58,56,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (59,51,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (59,67,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (60,51,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (60,67,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (61,51,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (61,67,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (62,47,'Requis');
INSERT INTO `APC_apprentissage_critique_as_module` VALUES (63,67,'Requis');
/*!40000 ALTER TABLE `APC_apprentissage_critique_as_module` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `APC_competence` WRITE;
/*!40000 ALTER TABLE `APC_competence` DISABLE KEYS */;
INSERT INTO `APC_competence` VALUES (1,'Concevoir et mettre en œuvre des systèmes informatiques','COMP_IDU1',NULL);
INSERT INTO `APC_competence` VALUES (2,'Collecter et traiter des données numériques','COMP_IDU2',NULL);
INSERT INTO `APC_competence` VALUES (3,'Gérer les usages des données numériques en lien avec le client','COMP_IDU3',NULL);
INSERT INTO `APC_competence` VALUES (4,'Gérer un projet informatique','COMP_IDU4',NULL);
/*!40000 ALTER TABLE `APC_competence` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `APC_competence_as_filiere_as_statut` WRITE;
/*!40000 ALTER TABLE `APC_competence_as_filiere_as_statut` DISABLE KEYS */;
/*!40000 ALTER TABLE `APC_competence_as_filiere_as_statut` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `APC_composante_essentielle` WRITE;
/*!40000 ALTER TABLE `APC_composante_essentielle` DISABLE KEYS */;
INSERT INTO `APC_composante_essentielle` VALUES (1,1,'En satisfaisant les besoins de l\'utilisateur avec une solution adaptée');
INSERT INTO `APC_composante_essentielle` VALUES (2,1,'En utilisant des méthodes et outils assurant la qualité du système (développement logiciel, gestion de projet informatique, standards qualité, sûreté, sécurité, amélioration continue)');
INSERT INTO `APC_composante_essentielle` VALUES (3,1,'En adoptant une approche systémique (aspects matériels et logiciels)');
INSERT INTO `APC_composante_essentielle` VALUES (4,1,'En communiquant de manière professionnelle (écrit, oral)');
INSERT INTO `APC_composante_essentielle` VALUES (5,2,'En utilisant de multiples outils d’acquisition  (scraping, des api web ou des dépôts de données structurées ou non)');
INSERT INTO `APC_composante_essentielle` VALUES (6,2,'En déployant des processus adaptés (mesure de la qualité, analyses statistiques, IA, rendus visuels...)');
INSERT INTO `APC_composante_essentielle` VALUES (7,2,'En déployant des analyses et visuels dans un but décisionnel ');
INSERT INTO `APC_composante_essentielle` VALUES (8,2,'En gérant un stockage adéquat de la donnée');
INSERT INTO `APC_composante_essentielle` VALUES (9,2,'En respectant les réglementations légales ');
INSERT INTO `APC_composante_essentielle` VALUES (13,3,'En respectant les réglementations en vigueur (RGPD, licences, ...)');
INSERT INTO `APC_composante_essentielle` VALUES (14,3,'En communiquant de manière professionnelle (oral, écrit)');
INSERT INTO `APC_composante_essentielle` VALUES (15,3,'En dimensionnant les solutions aux besoins');
INSERT INTO `APC_composante_essentielle` VALUES (16,4,'En exerçant un management opérationnel et stratégique');
INSERT INTO `APC_composante_essentielle` VALUES (17,4,'En coopérant avec des acteurs de professions et cultures différentes');
INSERT INTO `APC_composante_essentielle` VALUES (18,4,'En développant l\'initiative, l\'autonomie et l\'esprit d\'entreprenariat');
INSERT INTO `APC_composante_essentielle` VALUES (19,4,'En prenant en compte la dimension développement durable et RSE');
INSERT INTO `APC_composante_essentielle` VALUES (20,4,'En intégrant l’état de l’art des connaissances et des pratiques');
INSERT INTO `APC_composante_essentielle` VALUES (21,4,'En utilisant des méthodes et outils de gestion et de suivi du projet');
/*!40000 ALTER TABLE `APC_composante_essentielle` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `APC_niveau` WRITE;
/*!40000 ALTER TABLE `APC_niveau` DISABLE KEYS */;
INSERT INTO `APC_niveau` VALUES (1,1,1,'Pour une application simple 3-tiers intégrant une base de données et programmée en langage procédural ou objet');
INSERT INTO `APC_niveau` VALUES (2,1,2,'Pour une application N-tiers intégrant une base de données et programmée en langage objet et respectant les normes de qualité logiciel  ');
INSERT INTO `APC_niveau` VALUES (3,1,3,'Pour une application traitant des données du BigData');
INSERT INTO `APC_niveau` VALUES (4,2,1,'Pour des données simples, en petites quantités (<1000 tuples, <20 caractéristique, traitable en temps réel sur un PC de type bureautique)');
INSERT INTO `APC_niveau` VALUES (5,2,2,'Pour de grandes quantités de données nécessitant une ou plusieurs stations de calculs intensifs');
INSERT INTO `APC_niveau` VALUES (6,2,3,'Pour des données nécessitant des techniques de BigData (en volume, vélocité ou variété)');
INSERT INTO `APC_niveau` VALUES (7,3,1,'Appréhender les enjeux sociaux de la donnée');
INSERT INTO `APC_niveau` VALUES (8,3,2,'Intégrer le caractère socio-économique de la donnée');
INSERT INTO `APC_niveau` VALUES (9,3,3,'Protéger la donnée et les systèmes informatiques');
INSERT INTO `APC_niveau` VALUES (10,4,1,'Dans un cas simple, à partir d\'un cahier des charges donné');
INSERT INTO `APC_niveau` VALUES (11,4,2,'De façon semi-autonome à partir des besoins, dans un contexte socio-économique et culturel international');
INSERT INTO `APC_niveau` VALUES (12,4,3,'Dans un contexte autonome de d\'amélioration, d\'innovation ou de recherche');
/*!40000 ALTER TABLE `APC_niveau` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `APC_situation_professionnelle` WRITE;
/*!40000 ALTER TABLE `APC_situation_professionnelle` DISABLE KEYS */;
INSERT INTO `APC_situation_professionnelle` VALUES (1,1,'Ingénieur DevOps, Architecte big data, Architecte SI, Ingénieur d’études / Recherche et Développement');
INSERT INTO `APC_situation_professionnelle` VALUES (2,1,'ISOC831 Dimension Métier  (présentation de situation professionnelles par des entreprises.)');
INSERT INTO `APC_situation_professionnelle` VALUES (3,2,'DATA Engineer, DATA Analyst, Data scientist');
INSERT INTO `APC_situation_professionnelle` VALUES (4,2,'ISOC831 Dimension Métier (présentation de situation professionnelles par des entreprises.)');
INSERT INTO `APC_situation_professionnelle` VALUES (5,3,'Dev Front, Entreprenariat, Ingénieur sécu, Data Architecte');
INSERT INTO `APC_situation_professionnelle` VALUES (6,3,'ISOC831 Dimension Métier (présentation de situation professionnelles par des entreprises.)');
INSERT INTO `APC_situation_professionnelle` VALUES (7,4,'Conduite de projet informatique');
INSERT INTO `APC_situation_professionnelle` VALUES (8,4,'ISOC831 Dimension Métier (présentation de situation professionnelles par des entreprises.)');
/*!40000 ALTER TABLE `APC_situation_professionnelle` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `CLASS_absence` WRITE;
/*!40000 ALTER TABLE `CLASS_absence` DISABLE KEYS */;
/*!40000 ALTER TABLE `CLASS_absence` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `CLASS_session` WRITE;
/*!40000 ALTER TABLE `CLASS_session` DISABLE KEYS */;
/*!40000 ALTER TABLE `CLASS_session` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `ETU_classical_evaluation` WRITE;
/*!40000 ALTER TABLE `ETU_classical_evaluation` DISABLE KEYS */;
/*!40000 ALTER TABLE `ETU_classical_evaluation` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `ETU_competence_evaluation` WRITE;
/*!40000 ALTER TABLE `ETU_competence_evaluation` DISABLE KEYS */;
/*!40000 ALTER TABLE `ETU_competence_evaluation` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `ETU_polypoint` WRITE;
/*!40000 ALTER TABLE `ETU_polypoint` DISABLE KEYS */;
/*!40000 ALTER TABLE `ETU_polypoint` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `EXT_seance_planned` WRITE;
/*!40000 ALTER TABLE `EXT_seance_planned` DISABLE KEYS */;
/*!40000 ALTER TABLE `EXT_seance_planned` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_administratif` WRITE;
/*!40000 ALTER TABLE `LNM_administratif` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_administratif` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_administratif_as_role` WRITE;
/*!40000 ALTER TABLE `LNM_administratif_as_role` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_administratif_as_role` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_calendar` WRITE;
/*!40000 ALTER TABLE `LNM_calendar` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_calendar` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_enseignant` WRITE;
/*!40000 ALTER TABLE `LNM_enseignant` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_enseignant` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_enseignant_as_role` WRITE;
/*!40000 ALTER TABLE `LNM_enseignant_as_role` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_enseignant_as_role` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_enseignant_responsabilite_dimensions` WRITE;
/*!40000 ALTER TABLE `LNM_enseignant_responsabilite_dimensions` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_enseignant_responsabilite_dimensions` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_enseignant_responsabilites` WRITE;
/*!40000 ALTER TABLE `LNM_enseignant_responsabilites` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_enseignant_responsabilites` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_etudiant` WRITE;
/*!40000 ALTER TABLE `LNM_etudiant` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_etudiant` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_etudiant_as_groupe` WRITE;
/*!40000 ALTER TABLE `LNM_etudiant_as_groupe` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_etudiant_as_groupe` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_evaluation_type` WRITE;
/*!40000 ALTER TABLE `LNM_evaluation_type` DISABLE KEYS */;
INSERT INTO `LNM_evaluation_type` VALUES (1,'Notation / 20','20','0','10',NULL,NULL);
INSERT INTO `LNM_evaluation_type` VALUES (2,'Notation / 10','10','0','5',NULL,NULL);
INSERT INTO `LNM_evaluation_type` VALUES (3,'Notation / 5','5','0','2.5',NULL,NULL);
INSERT INTO `LNM_evaluation_type` VALUES (4,'Échelle d’évaluation ECTS','A','F','E','{F,Fx,E,D,C,C,B,A}','{Un travail supplémentaire considérable est nécessaire; Un travail supplémentaire est nécessaire pour l\'octroi d\'un crédit; Les résultats satisfont aux critères minimaux; Travail honnête, mais comportant des lacunes importantes; Généralement bon, malgré un certain nombre d\'insuffisances notables; Résultats supérieurs à la moyenne, malgré un certain nombre d\'insuffisances; Résultats remarquables, avec seulement quelques insuffisances mineures}');
INSERT INTO `LNM_evaluation_type` VALUES (5,'Echelle de notation ABCDE simple','A','E','C','{E,D,C,B,A}','{Non évaluable; N\'atteint pas le minimum requis; Minimum requis atteint avec des lacunes importantes ne remettant pas en cause la compréhension du sujet; Bonne maitrise du sujet avec des lacunes mineures à combler; Excellente maitrise du sujet, quelques lacunes négligeables nécessitant des approfondissements acceptables ');
INSERT INTO `LNM_evaluation_type` VALUES (6,'Echelle de notation ABCDE +- simple','A+','E-','C-','{A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,E+,E,E-}',NULL);
INSERT INTO `LNM_evaluation_type` VALUES (7,'Binaire','Validé','Non validé','Validé','{Non validé, Validé}',NULL);
INSERT INTO `LNM_evaluation_type` VALUES (8,'Compétence 4 niveaux','A','D','B','{A,B,C,D}','{Audela des attentes, Objectif atteint, Objectif non atteint, Non évalué}');
/*!40000 ALTER TABLE `LNM_evaluation_type` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_filiere` WRITE;
/*!40000 ALTER TABLE `LNM_filiere` DISABLE KEYS */;
INSERT INTO `LNM_filiere` VALUES (3,'IDU','Informatique Données Usages',NULL);
INSERT INTO `LNM_filiere` VALUES (4,'MM','Mécanique Mécatronique Matériaux Composites',NULL);
INSERT INTO `LNM_filiere` VALUES (5,'SEA','Systèmes Embarqués Automatisation Capteurs',NULL);
INSERT INTO `LNM_filiere` VALUES (6,'BAT','Bâtiment Écoconstruction Énergie',NULL);
INSERT INTO `LNM_filiere` VALUES (7,'EIT','Écologie Industrielle et Territoriale',NULL);
/*!40000 ALTER TABLE `LNM_filiere` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_groupe` WRITE;
/*!40000 ALTER TABLE `LNM_groupe` DISABLE KEYS */;
INSERT INTO `LNM_groupe` VALUES (1,'IDU3',5,1);
INSERT INTO `LNM_groupe` VALUES (2,'IDU4',15,1);
INSERT INTO `LNM_groupe` VALUES (3,'IDU5',16,1);
INSERT INTO `LNM_groupe` VALUES (4,'IDU3_TD1',5,2);
INSERT INTO `LNM_groupe` VALUES (5,'IDU4_TD1',15,2);
INSERT INTO `LNM_groupe` VALUES (6,'IDU5_TD1',16,2);
INSERT INTO `LNM_groupe` VALUES (7,'IDU3_TP11',5,3);
INSERT INTO `LNM_groupe` VALUES (8,'IDU3_TP12',5,3);
INSERT INTO `LNM_groupe` VALUES (9,'IDU4_TP11',15,3);
INSERT INTO `LNM_groupe` VALUES (10,'IDU4_TP12',15,3);
INSERT INTO `LNM_groupe` VALUES (11,'IDU5_TP11',16,3);
INSERT INTO `LNM_groupe` VALUES (12,'IDU5_TP12',16,3);
INSERT INTO `LNM_groupe` VALUES (13,'MM3',17,1);
INSERT INTO `LNM_groupe` VALUES (14,'MM4',18,1);
INSERT INTO `LNM_groupe` VALUES (15,'MM5',19,1);
INSERT INTO `LNM_groupe` VALUES (25,'SEA3',20,1);
INSERT INTO `LNM_groupe` VALUES (26,'SEA4',21,1);
INSERT INTO `LNM_groupe` VALUES (27,'SEA5',22,1);
INSERT INTO `LNM_groupe` VALUES (37,'BAT3',23,1);
INSERT INTO `LNM_groupe` VALUES (38,'BAT4',24,1);
INSERT INTO `LNM_groupe` VALUES (39,'BAT5',25,1);
INSERT INTO `LNM_groupe` VALUES (49,'EIT3',26,1);
INSERT INTO `LNM_groupe` VALUES (50,'EIT4',27,1);
INSERT INTO `LNM_groupe` VALUES (51,'EIT5',28,1);
INSERT INTO `LNM_groupe` VALUES (69,'SEA3_TD1',20,2);
INSERT INTO `LNM_groupe` VALUES (70,'SEA4_TD1',21,2);
INSERT INTO `LNM_groupe` VALUES (71,'SEA5_TD1',22,2);
INSERT INTO `LNM_groupe` VALUES (72,'SEA3_TP11',20,3);
INSERT INTO `LNM_groupe` VALUES (73,'SEA3_TP12',20,3);
INSERT INTO `LNM_groupe` VALUES (74,'SEA4_TP11',21,3);
INSERT INTO `LNM_groupe` VALUES (75,'SEA4_TP12',21,3);
INSERT INTO `LNM_groupe` VALUES (76,'SEA5_TP11',22,3);
INSERT INTO `LNM_groupe` VALUES (77,'SEA5_TP12',22,3);
/*!40000 ALTER TABLE `LNM_groupe` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_groupe_type` WRITE;
/*!40000 ALTER TABLE `LNM_groupe_type` DISABLE KEYS */;
INSERT INTO `LNM_groupe_type` VALUES (1,'PROMO','toute la promo');
INSERT INTO `LNM_groupe_type` VALUES (2,'TD','groupe de TD');
INSERT INTO `LNM_groupe_type` VALUES (3,'TP','groupe de TP');
/*!40000 ALTER TABLE `LNM_groupe_type` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_origine` WRITE;
/*!40000 ALTER TABLE `LNM_origine` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_origine` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_promo` WRITE;
/*!40000 ALTER TABLE `LNM_promo` DISABLE KEYS */;
INSERT INTO `LNM_promo` VALUES (5,3,1,3,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (15,3,1,4,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (16,3,1,5,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (17,4,1,3,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (18,4,1,4,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (19,4,1,5,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (20,5,1,3,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (21,5,1,4,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (22,5,1,5,NULL,'Annecy',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (23,6,1,3,NULL,'Chambéry',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (24,6,1,4,NULL,'Chambéry',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (25,6,1,5,NULL,'Chambéry',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (26,7,1,3,NULL,'Chambéry',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (27,7,1,4,NULL,'Chambéry',1,1,2,NULL);
INSERT INTO `LNM_promo` VALUES (28,7,1,5,NULL,'Chambéry',1,1,2,NULL);
/*!40000 ALTER TABLE `LNM_promo` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_rendu_module` WRITE;
/*!40000 ALTER TABLE `LNM_rendu_module` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_rendu_module` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_rendu_module_as_enseignant` WRITE;
/*!40000 ALTER TABLE `LNM_rendu_module_as_enseignant` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_rendu_module_as_enseignant` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_rendu_module_as_etudiant` WRITE;
/*!40000 ALTER TABLE `LNM_rendu_module_as_etudiant` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_rendu_module_as_etudiant` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_role` WRITE;
/*!40000 ALTER TABLE `LNM_role` DISABLE KEYS */;
INSERT INTO `LNM_role` VALUES (5,'Directeur');
INSERT INTO `LNM_role` VALUES (6,'Directeur adjoint en charge de la formation');
INSERT INTO `LNM_role` VALUES (4,'Directeur adjoint en charge de la recherche');
INSERT INTO `LNM_role` VALUES (2,'Relation entreprises');
INSERT INTO `LNM_role` VALUES (3,'Relations internationales');
INSERT INTO `LNM_role` VALUES (7,'Responsable de la scolarité');
INSERT INTO `LNM_role` VALUES (1,'Responsable études');
/*!40000 ALTER TABLE `LNM_role` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_seance_type` WRITE;
/*!40000 ALTER TABLE `LNM_seance_type` DISABLE KEYS */;
INSERT INTO `LNM_seance_type` VALUES (1,'CM','cours magistral');
INSERT INTO `LNM_seance_type` VALUES (2,'TD','travaux dirigés');
INSERT INTO `LNM_seance_type` VALUES (3,'TP','travaux pratique');
INSERT INTO `LNM_seance_type` VALUES (4,'Exam','Examen');
INSERT INTO `LNM_seance_type` VALUES (5,'PROJ','en autonomie');
/*!40000 ALTER TABLE `LNM_seance_type` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_semestre` WRITE;
/*!40000 ALTER TABLE `LNM_semestre` DISABLE KEYS */;
INSERT INTO `LNM_semestre` VALUES (1,'S1');
INSERT INTO `LNM_semestre` VALUES (10,'S10');
INSERT INTO `LNM_semestre` VALUES (2,'S2');
INSERT INTO `LNM_semestre` VALUES (3,'S3');
INSERT INTO `LNM_semestre` VALUES (4,'S4');
INSERT INTO `LNM_semestre` VALUES (5,'S5');
INSERT INTO `LNM_semestre` VALUES (6,'S6');
INSERT INTO `LNM_semestre` VALUES (7,'S7');
INSERT INTO `LNM_semestre` VALUES (8,'S8');
INSERT INTO `LNM_semestre` VALUES (9,'S9');
/*!40000 ALTER TABLE `LNM_semestre` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_stage` WRITE;
/*!40000 ALTER TABLE `LNM_stage` DISABLE KEYS */;
/*!40000 ALTER TABLE `LNM_stage` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_statut` WRITE;
/*!40000 ALTER TABLE `LNM_statut` DISABLE KEYS */;
INSERT INTO `LNM_statut` VALUES (1,'FISE','Formation initiale sous statut étudiant');
INSERT INTO `LNM_statut` VALUES (2,'FISA','Formation initiale sous statut apprenti');
INSERT INTO `LNM_statut` VALUES (3,'FISEA','Formation initiale sous statut étudiant puis apprenti');
INSERT INTO `LNM_statut` VALUES (4,'FISECP','Formation initiale sous statut étudiant puis en contrat pro');
/*!40000 ALTER TABLE `LNM_statut` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_universite` WRITE;
/*!40000 ALTER TABLE `LNM_universite` DISABLE KEYS */;
INSERT INTO `LNM_universite` VALUES (1,'Fachhochschule Aachen','Fachhochschule Aachen','Aachen',NULL,'Allemagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (2,'Hochschule Heilbronn','Hochschule Heilbronn','Heilbronn',NULL,'Allemagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (3,'Hochschule Kaiserslautern','Hochschule Kaiserslautern','Kaiserslautern',NULL,'Allemagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (4,'TU Bergakademie Freiberg','TU Bergakademie Freiberg','Freiberg',NULL,'Allemagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (5,'Hochschule Magdeburg','Hochschule Magdeburg','Magdebourg',NULL,'Allemagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (6,'TU Braunschweig Carolo Wilhelmina','TU Braunschweig Carolo Wilhelmina','Braunschweig',NULL,'Allemagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (7,'Universität Stuttgart','Universität Stuttgart','Stuttgart',NULL,'Allemagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (8,'Universidad Nacional de La Plata (UNLP)','Universidad Nacional de La Plata (UNLP)','La Plata',NULL,'Argentine',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (9,'Universidad Nacional de Cuyo','Universidad Nacional de Cuyo','Mendoza',NULL,'Argentine',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (10,'Fachhochschule Technikum Wien','Fachhochschule Technikum Wien','Vienne',NULL,'Autriche',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (11,'Université de Liège','Université de Liège','Liège',NULL,'Belgique',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (12,'Haute Ecole de la Communauté Française en Hainaut','Haute Ecole de la Communauté Française en Hainaut','Mons',NULL,'Belgique',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (13,'Haute Ecole de la Province de Liège','Haute Ecole de la Province de Liège','Liège',NULL,'Belgique',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (14,'Universidade Federal de Viçosa','Universidade Federal de Viçosa','Viçosa',NULL,'Brésil',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (15,'Ecole de Technologie Supérieure (ETS)','Ecole de Technologie Supérieure (ETS)','Montréal',NULL,'Canada',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (16,'Escuela Tecnica Superior de Ingeneria Informatica/Universidad de Sevilla','ETSII/Universidad de Sevilla','Sevilla',NULL,'Espagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (17,'Universidad Zaragoza','Universidad Zaragoza','Saragosse',NULL,'Espagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (18,'Escuela Tecnica Superior de Ingenieria de Sistemas Informaticos / Universidad Politecnica Madrid','ETSISI / Universidad Politecnica Madrid','Madrid',NULL,'Espagne',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (19,'University of Hyogo','University of Hyogo','Hyogo',NULL,'Japon',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (20,'Norges Teknisk-Naturvitenskaplige Universitet (NTNU)','NTNU','Trondheim',NULL,'Norvège',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (21,'Universitatea de Vest din Timisoara','Universitatea de Vest din Timisoara','Timisoara',NULL,'Roumanie',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
INSERT INTO `LNM_universite` VALUES (22,'BFH Bern University of Applied Sciences','BFH Bern University of Applied Sciences','Bern',NULL,'Suisse',NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0);
/*!40000 ALTER TABLE `LNM_universite` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `LNM_universite_as_promo` WRITE;
/*!40000 ALTER TABLE `LNM_universite_as_promo` DISABLE KEYS */;
INSERT INTO `LNM_universite_as_promo` VALUES (1,5,2);
INSERT INTO `LNM_universite_as_promo` VALUES (12,5,3);
/*!40000 ALTER TABLE `LNM_universite_as_promo` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAQUETTE_dependance_sequence` WRITE;
/*!40000 ALTER TABLE `MAQUETTE_dependance_sequence` DISABLE KEYS */;
/*!40000 ALTER TABLE `MAQUETTE_dependance_sequence` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAQUETTE_discipline` WRITE;
/*!40000 ALTER TABLE `MAQUETTE_discipline` DISABLE KEYS */;
INSERT INTO `MAQUETTE_discipline` VALUES (5,'Automatique');
INSERT INTO `MAQUETTE_discipline` VALUES (8,'Elec.');
INSERT INTO `MAQUETTE_discipline` VALUES (1,'Informatique');
INSERT INTO `MAQUETTE_discipline` VALUES (6,'Langue');
INSERT INTO `MAQUETTE_discipline` VALUES (2,'Mathématiques');
INSERT INTO `MAQUETTE_discipline` VALUES (4,'PACI');
INSERT INTO `MAQUETTE_discipline` VALUES (9,'Projet');
INSERT INTO `MAQUETTE_discipline` VALUES (7,'SHES');
INSERT INTO `MAQUETTE_discipline` VALUES (3,'Traitement du signal');
/*!40000 ALTER TABLE `MAQUETTE_discipline` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAQUETTE_learning_unit` WRITE;
/*!40000 ALTER TABLE `MAQUETTE_learning_unit` DISABLE KEYS */;
INSERT INTO `MAQUETTE_learning_unit` VALUES (1,'UE501','Passerelle vers le parcours professionnel',5);
INSERT INTO `MAQUETTE_learning_unit` VALUES (2,'UE503','Sciences de l\'ingénieur IDU1',5);
INSERT INTO `MAQUETTE_learning_unit` VALUES (3,'UE502','Sciences et outils de l\'ingénieur',5);
INSERT INTO `MAQUETTE_learning_unit` VALUES (4,'UE601','Passerelle vers le parcours professionnel',5);
INSERT INTO `MAQUETTE_learning_unit` VALUES (5,'UE602','Mathématiques et algorithmique',5);
INSERT INTO `MAQUETTE_learning_unit` VALUES (6,'UE603','Informatique et Conception',5);
INSERT INTO `MAQUETTE_learning_unit` VALUES (7,'UE604','Environnement et Applications',5);
INSERT INTO `MAQUETTE_learning_unit` VALUES (8,'UE701','Passerelle vers le parcours professionnel',15);
INSERT INTO `MAQUETTE_learning_unit` VALUES (9,'UE702','Mathématiques et Données ',15);
INSERT INTO `MAQUETTE_learning_unit` VALUES (10,'UE703',' Informatique et Conception ',15);
INSERT INTO `MAQUETTE_learning_unit` VALUES (11,'UE704','Visualisation et Gouvernance',15);
INSERT INTO `MAQUETTE_learning_unit` VALUES (12,'UE801','Passerelle vers le parcours professionnel',15);
INSERT INTO `MAQUETTE_learning_unit` VALUES (13,'UE802','Stage',15);
INSERT INTO `MAQUETTE_learning_unit` VALUES (14,'UE803','Données et aide à la décision',15);
INSERT INTO `MAQUETTE_learning_unit` VALUES (15,'UE804',' Informatique et Conception',15);
INSERT INTO `MAQUETTE_learning_unit` VALUES (16,'UE901','Passerelle vers le parcours professionnel',16);
INSERT INTO `MAQUETTE_learning_unit` VALUES (17,'UE902','Optimisation et HPC',16);
INSERT INTO `MAQUETTE_learning_unit` VALUES (18,'UE903','Données et Aide la décision',16);
/*!40000 ALTER TABLE `MAQUETTE_learning_unit` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAQUETTE_module` WRITE;
/*!40000 ALTER TABLE `MAQUETTE_module` DISABLE KEYS */;
INSERT INTO `MAQUETTE_module` VALUES (1,'INFO101','Introduction à l\'algorithmique',3.0,1,1,6,9,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (2,'INFO202','Programmation et algorithmique',3.0,1,2,6,9,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (3,'INFO201','Système d\'exploitation',3.0,1,2,6,6,15,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (12,'INFO501','Numération et Algorithmique',3.0,1,5,10.5,26.5,NULL,NULL,NULL,NULL,'- Est-il envisageable de programmer des séances de td (au moins 2) sur machine ?\r\n(ces séances se passeraient en salle de TP, avec 2 étudiants par machine)\r\n\r\n- Est-il possible de grouper les séances de TP n°2, 3 et 4 soit toutes les 3 avant Noël, soit toutes les 3 après Noël.\r\nEn effet, ces séances correspondent à un seul sujet de tp, et quand il y a la coupure de Noël, cela ne facilite pas les choses.\r\n\r\n* Enchainement C/TD/TP :\r\n\r\nC1\r\nC2\r\nC3\r\n    TD1\r\nC4\r\n    TD2\r\nC5\r\n    TD3\r\nC6\r\n    TD4\r\nC7\r\n    TD5, TD6\r\n        TP1\r\n    TD7\r\n        TP2, TP3, TP4\r\n\r\nLe CC est à placer après la fin complète du module.');
INSERT INTO `MAQUETTE_module` VALUES (13,'INFO502','Initiation aux BD',1.5,1,5,6,4.5,12,NULL,NULL,NULL,'CM en amphi TD en salles de TD TP en salles machines Exam pas forcément en parallèle sur les 2 sites Si possible placer tous les CM, TD et TP entre la rentrée et Toussaint et placer l\'exam après la Toussaint Regrouper, si possible, la même 1/2 journée les TD des enseignants qui ont 2 groupes. Ordre des cours : CM1 -> CM2 -> TD1 -> CM3 -> TD2 -> TD3 -> TP1 -> TP2 -> TP3 -> Exam');
INSERT INTO `MAQUETTE_module` VALUES (14,'INFO641','Conception et Programmation Orienté Objet',2.5,1,6,9,21,8,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (15,'INFO642','Base de Données et Technologies Web',NULL,1,6,8.5,7.5,20,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (16,'INFO743','Réseaux et Systèmes répartis',2.5,1,7,18,16,4,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (17,'INFO741','Systèmes embarqués et systèmes d\'exploitation',NULL,1,7,9,3,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (18,'INFO742','Méthodes de développement logiciel et qualité',NULL,1,7,12.5,23.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (19,'INFO790','Informatique',NULL,1,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (20,'INFO851_MMT','Système embarqué 1',NULL,1,8,7.5,9,20,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (21,'INFO890','Algorithmique et Base de Données',NULL,1,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (22,'EASI890_CM','Système embarqué',NULL,1,8,8,NULL,32,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (23,'INFO951','Système embarqué 2',NULL,1,9,9,3,24,NULL,NULL,NULL,'Les CM est l\'exam sont communs avec INFO941');
INSERT INTO `MAQUETTE_module` VALUES (24,'INFO941','Système embarqué 2',NULL,1,9,9,27,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (25,'INFO942','Apprentissage automatique et fouille de données',NULL,1,9,12,NULL,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (26,'INFO943_SNI','Internet des objets',NULL,1,9,3,9,24,NULL,NULL,NULL,'1 seul groupe de TP dans 2 salles TP : Projet');
INSERT INTO `MAQUETTE_module` VALUES (27,'PROJ942','Reconnaissance de visages',NULL,1,9,NULL,NULL,36,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (32,'PROJ641','APP',NULL,1,6,NULL,NULL,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (33,'PROJ741','APP',NULL,1,7,NULL,NULL,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (34,'PROJ841','APP',NULL,1,8,NULL,NULL,40,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (35,'PROJ943','APP',NULL,1,9,NULL,NULL,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (36,'INFO305','Programmation objet I',3.0,1,3,6,9,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (39,'INFO402','Programmation orientée objet II',3.0,1,4,6,9,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (41,'INFO404','Bases de données',3.0,1,4,6,9,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (42,'ISOC531_IDU','Sociétés numériques',3.0,1,5,13.5,22.5,4,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (43,'PROJ531','Gestion de projets',3.0,1,5,6,6,28,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (44,'INFO631','Logique et Programmation',3.0,1,6,10.5,10.5,20,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (45,'MATH531','Graphes et Langages',3.0,1,5,12,12,16,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (46,'INFO632','Systèmes d’exploitation et Virtualisation',3.0,1,6,10.5,13.5,16,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (47,'ISOC631','Plateformes collaboratives',3.0,1,6,13.5,15,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (48,'PROJ632','Projet Data Science',3.0,1,6,NULL,30,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (49,'PROJ631','Projet Algorithmique',4.0,1,6,NULL,42,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (50,'DATA731','Modélisation Stochastique',3.0,1,7,12,NULL,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (51,'INFO731_IDU','Sécurité et Cryptographie',3.0,1,7,13.5,22.5,4,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (52,'INFO732','Comportement et Modélisation Dynamique',2.5,1,7,7.5,6,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (53,'PROJ731','Analyse et front_DashPlotly de données',2.0,1,7,NULL,20,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (54,'DATA732','Analyse et front_DashPlotly de données',3.0,1,7,12,23.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (55,'INFO734','Développement Full Stack',3.0,1,7,12,24,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (56,'ISOC731','Économie et gouvernance de la donnée',3.0,1,7,15,21,4,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (57,'DATA831','Big Data',1.0,1,8,7.5,NULL,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (58,'DATA832','Machine Learning 1',2.5,1,8,9,9,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (59,'INFO831','Informatique décisionnelle',2.5,1,8,9,9,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (60,'ISOC831','Dimension métiers',1.5,1,8,30,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (61,'INFO832','Qualité et tests logiciel',2.5,1,8,12,12,16,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (62,'INFO833','Systèmes distribués à large échelle',2.5,1,8,12,13.5,15,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (63,'INFO834','Bases de données distribuées',2.5,1,8,7.5,7.5,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (64,'PROJ831','Projet Informatique Données et Usages',1.5,1,8,NULL,20,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (65,'INFO931','Optimisation et aide à la décision multicritère',3.0,1,9,12,12,16,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (66,'INFO932','Calcul haute performance et Cloud Computing',3.0,1,9,7.5,7.5,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (67,'PROJ931','Projet Usages',4.0,1,9,NULL,NULL,40,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (68,'DATA931','Machine Learning',3.0,1,9,12,12,16,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (69,'ISOC931','Innovation et Recherche',3.0,1,9,6,12,20,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (70,'PROJ932','Projet Data Science',4.0,1,9,NULL,NULL,40,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (72,'INFO850','Informatique - Computer science',NULL,1,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (73,'INFO841','Sécurité des systèmes cyber-physiques',NULL,1,8,7.5,4.5,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (74,'INFO633','APP - Bases de données et technologies web',2.5,1,6,8.5,7.5,20,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (75,'INFO405','Projet de programmation',3.0,1,4,NULL,6,15,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (76,'LANG501','Anglais',4.0,6,5,NULL,40.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (77,'SHES501','Sport',1.0,7,5,NULL,21,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (78,'SHES505','Simulation de gestion d\'entreprise',1.0,7,5,NULL,19.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (79,'LANG500','Soutien anglais',0.0,6,5,NULL,12,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (80,'DDRS501','Développement Durable',1.5,7,5,12,9,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (81,'EASI501','Electricité',3.0,8,5,13.5,15,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (82,'MATH500','Soutien en Mathématiques ',0.0,2,5,NULL,21,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (83,'MATH501','Mathématiques',3.0,2,5,21,19.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (84,'EASI541','Automatisation',3.0,5,5,6,13.5,20,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (85,'LANG600','Soutien Anglais ',0.0,6,6,NULL,12,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (86,'LANG601','Anglais',4.0,6,6,NULL,40.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (87,'PROJ601','Stage découverte du milieu professionnel',0.0,9,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (88,'SHES601','Gestion financière',1.0,7,6,10.5,9,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (89,'SHES602','Initiation au droit',1.0,7,6,15,4.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (90,'PROJ600','Stage facultatif',0.0,9,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (91,'MATH641','Mathématiques',3.0,2,6,18,18,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (93,'LANG700','Soutien Anglais',0.0,6,7,NULL,6,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (94,'SHES703','Visualisation et Gouvernance',1.5,7,7,NULL,15,4,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (95,'SHES704','Créativité et management de l\'innovation',1.5,7,7,NULL,25.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (96,'LANG701','Anglais',3.0,6,7,NULL,40.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (97,'LANG702','Anglais + LV2',3.0,6,7,NULL,35,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (98,'MATH741','Probabilités ‐ Statistique',2.0,2,7,18,18,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (100,'LANG800','Soutien Anglais',0.0,6,8,NULL,6,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (101,'SHES802','Système de Management Intégré QSE (Qualité Sécurité Environnement)',1.5,7,8,9,10.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (102,'SHES803','Théorie des organisations',1.5,7,8,9,9,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (103,'LANG801','Anglais (Niveau TOEIC non atteint)',3.0,6,8,NULL,40.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (104,'LANG802','Langues vivantes (Niveau TOEIC atteint)',3.0,6,8,NULL,35,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (105,'PROJ801','Stage assistant ingénieur',6.0,9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (112,'LANG901','Anglais (Niveau TOEIC non atteint)',2.5,6,9,NULL,40.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (113,'LANG902','Langues vivantes (Niveau TOEIC atteint)',2.5,6,9,NULL,35,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (114,'SHES901','Techniques de management',1.5,7,9,15,7.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (115,'PROJ901','Projet Recherche et Développement ',6.0,9,9,NULL,NULL,40,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (121,'PACI641','Matériaux actifs et intelligents pour l\'instrumentation',NULL,4,6,21,15,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (122,'PACI642','Optique appliquée et transmission optique',NULL,4,6,14.5,15.5,8,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (123,'EASI641','Signaux et systèmes',NULL,3,6,12,12,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (124,'EASI642','Signal et image : opérateurs de base',NULL,3,6,13.5,13.5,9,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (125,'MATH642','Mathématiques spécialisées',NULL,2,6,18,18,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (130,'EASI744','Automatique - Stabilité et commande de systèmes',NULL,5,7,10,10.5,16,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (131,'PACI741','Electronique d\'instrumentation : notions essentielles pour l\'ingénieur',NULL,4,7,12,12,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (132,'PACI742','Systèmes d\'acquisition de données ',NULL,4,7,4.5,NULL,32,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (133,'EASI741','Signaux aléatoires',NULL,3,7,12,12,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (134,'EASI843','Automatisation décentralisée',NULL,5,8,NULL,NULL,24,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (135,'PACI841','Physique expérimentale, mesures, capteurs et instrumentation',NULL,4,8,15,13.5,64,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (136,'EASI842','Analyse d\'image et vision par ordinateur',NULL,3,8,15,13.5,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (137,'EASI844','Modèles des systèmes à évènements discrets et applications',NULL,5,8,9,19.5,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (141,'EASI943','Approche d\'état en automatique : représentation, commande et observation',NULL,5,9,25.5,25.5,20,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (142,'EASI941','Systèmes communicants, capteurs communicants',NULL,8,9,NULL,NULL,36,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (143,'EASI942','Imagerie 3D : acquisition, reconstruction, applications',NULL,3,9,13.5,10.5,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (144,'LANG502_ALT','Anglais Alternants',3.0,6,5,NULL,36,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (145,'SHES532_ALT','Ressources et dynamique personnelle et professionnelle',2.0,7,5,12,12,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (146,'LANG602_ALT','Anglais Alternants',3.0,6,6,NULL,36,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (147,'ENTR531_ALT','Mission en entreprise',2.0,1,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (148,'ENTR532_ALT','Immersion en entreprise',6.0,7,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (149,'ENTR631_ALT','Mission en entreprise',2.0,1,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (150,'ENTR632_ALT','Gestion de projet informatique',6.0,7,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (151,'DDRS631_ALT','Numérique Durable',1.0,7,6,0,15,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (152,'ENTR731_ALT','Mission en entreprise',2.0,1,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (153,'ENTR732_ALT','Projet Technique',6.0,7,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (154,'ENTR831_ALT','Mission en entreprise',2.0,1,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (155,'ENTR832_ALT','Projet Data',6.0,1,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (156,'ENTR931_ALT','Mission en entreprise',2.0,1,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (157,'ENTR932_ALT','Projet IDU',6.0,1,9,NULL,NULL,NULL,NULL,NULL,NULL,'Projet Usages + Data Science');
INSERT INTO `MAQUETTE_module` VALUES (159,'LANG702_ALT','Anglais Alternant (Niveau TOEIC non atteint) ',2.0,6,7,NULL,36,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (160,'LANG701_ALT','Anglais Alternant (Niveau TOEIC atteint) ',2.0,6,7,NULL,32,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (161,'LANG802_ALT','Anglais (Niveau TOEIC non atteint)',2.0,6,8,NULL,36,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (162,'LANG801_ALT','Anglais (Niveau TOEIC atteint)',2.0,6,8,NULL,32,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (163,'LANG902_ALT','Anglais (Niveau TOEIC non atteint)',2.0,6,9,NULL,36,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (164,'LANG901_ALT','Anglais (Niveau TOEIC atteint)',2.0,6,9,NULL,32,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (165,'INFO531_ALT','BD et algorithmique',3.0,1,5,NULL,40,NULL,NULL,NULL,NULL,'Répartition des heures à faire');
INSERT INTO `MAQUETTE_module` VALUES (166,'MATH532_ALT','Mise à niveau maths discrètes générales',3.0,2,5,NULL,40,NULL,NULL,NULL,NULL,'Répartition des heures à faire');
INSERT INTO `MAQUETTE_module` VALUES (167,'SHES631_ALT','management de projets informatiques',1.5,7,6,10.5,10.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (168,'MATH631_ALT','Proba Stat',2.5,2,6,15,15,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (169,'SHES731_ALT','Ouverture SHES',1.0,7,7,NULL,14,NULL,NULL,NULL,NULL,'géopolitique, biais de la donnée, discrimination, numérique et environnement...\r\n6 séances de 3,5h TD');
INSERT INTO `MAQUETTE_module` VALUES (170,'MATH731_ALT','Maths discrètes avancées',1.5,2,7,10.5,10.5,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (171,'SHES831_ALT','Environnement légal et protection de la donnée personnelle ',2.0,7,8,NULL,24,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (172,'MATH831_ALT','Représentation géométrique de la donnée',3.0,2,8,18,18,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (173,'SHES931_ALT','Ouverture SHES',3.0,7,9,NULL,35,NULL,NULL,NULL,NULL,'géopolitique, biais de la donnée, discrimination, numérique et environnement...\r\n6 séances de 3,5h TD');
INSERT INTO `MAQUETTE_module` VALUES (174,'MATH931_ALT','Maths pour le deep',3.0,2,9,18,18,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (175,'PROJ931_ALT','Projet R&D',2.0,1,9,NULL,28,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (176,'INFO530_ALT','Evaluation Compétences Info',1.0,1,5,NULL,12,NULL,NULL,NULL,NULL,'Évaluation des compétences et remise à niveau en informatique');
INSERT INTO `MAQUETTE_module` VALUES (177,'INFO403','Programmation C',3.0,1,4,6,9,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (178,'INFO701_AM','Development and deployment frameworks ',1.0,1,7,NULL,NULL,12,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (179,'PROJ541_SNI','Découverte expérimentale de la spécialité SNI',3.0,1,5,NULL,NULL,16,NULL,NULL,NULL,NULL);
INSERT INTO `MAQUETTE_module` VALUES (180,'PROJ832_IDU','Flux de Données et Accès Concurrents',1.5,1,8,4,16,NULL,NULL,NULL,NULL,NULL);
/*!40000 ALTER TABLE `MAQUETTE_module` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAQUETTE_module_as_learning_unit` WRITE;
/*!40000 ALTER TABLE `MAQUETTE_module_as_learning_unit` DISABLE KEYS */;
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (1,1);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (76,1);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (77,1);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (78,1);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (79,1);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (42,2);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (43,2);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (45,2);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (12,3);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (13,3);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (80,3);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (81,3);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (82,3);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (83,3);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (84,3);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (85,4);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (86,4);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (87,4);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (88,4);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (89,4);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (90,4);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (44,5);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (49,5);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (91,5);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (14,6);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (74,6);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (46,7);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (47,7);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (48,7);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (93,8);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (94,8);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (95,8);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (96,8);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (97,8);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (50,9);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (51,9);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (98,9);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (16,10);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (52,10);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (53,10);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (54,11);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (55,11);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (56,11);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (100,12);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (101,12);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (102,12);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (103,12);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (104,12);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (105,13);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (57,14);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (58,14);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (59,14);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (64,14);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (60,15);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (61,15);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (62,15);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (63,15);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (112,16);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (113,16);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (114,16);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (115,16);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (65,17);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (66,17);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (67,17);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (68,18);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (69,18);
INSERT INTO `MAQUETTE_module_as_learning_unit` VALUES (70,18);
/*!40000 ALTER TABLE `MAQUETTE_module_as_learning_unit` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAQUETTE_module_sequencage` WRITE;
/*!40000 ALTER TABLE `MAQUETTE_module_sequencage` DISABLE KEYS */;
/*!40000 ALTER TABLE `MAQUETTE_module_sequencage` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MAQUETTE_module_sequence` WRITE;
/*!40000 ALTER TABLE `MAQUETTE_module_sequence` DISABLE KEYS */;
/*!40000 ALTER TABLE `MAQUETTE_module_sequence` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MOB_assignment` WRITE;
/*!40000 ALTER TABLE `MOB_assignment` DISABLE KEYS */;
/*!40000 ALTER TABLE `MOB_assignment` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MOB_filiere_quotas` WRITE;
/*!40000 ALTER TABLE `MOB_filiere_quotas` DISABLE KEYS */;
/*!40000 ALTER TABLE `MOB_filiere_quotas` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MOB_partner_university` WRITE;
/*!40000 ALTER TABLE `MOB_partner_university` DISABLE KEYS */;
INSERT INTO `MOB_partner_university` VALUES (1,'Fachhochschule Aachen','DE-FA','Allemagne',NULL,'Bayernallee 11, 52066 Aachen',50.755672,6.096229,'https://www.fh-aachen.de/en/','Allemand, Anglais',3,7,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (2,'Fachhochschule Heilbronn','DE-FH','Allemagne',NULL,'Max-Planck-Straße 39, Heilbronn',49.121966,9.211413,'https://www.hs-heilbronn.de/en','Allemand, Anglais',2,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (3,'Hochschule Kaiserslautern','DE-HK','Allemagne',NULL,'Schoenstraße 11, 67659 Kaiserslautern',49.447205,7.759804,'https://www.hs-kl.de/en/','Allemand, Anglais',6,6,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (4,'TU Bergakademie Freiberg','DE-TBF','Allemagne',NULL,'Akademiestraße 6, 09599 Freiberg',50.918249,13.340845,'https://tu-freiberg.de/en','Allemand, Anglais',1,1,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (5,'Hochschule Magdeburg-Stendal','DE-HM','Allemagne',NULL,'Postfach 3655, 39011 Magdeburg',52.141862,11.675858,'https://www.h2.de/no_cache/en/','Allemand',1,1,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (6,'TU Braunschweig Carolo Wilhelmina','DE-TBCW','Allemagne',NULL,'Universitätsplatz 2, 38106 Braunschweig',52.273596,10.530172,'https://www.tu-braunschweig.de/en/','Allemand',0,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (7,'Universität Stuttgart','DE-US','Allemagne',NULL,'Postfach 1060037, 70049 Stuttgart',48.741452,9.098761,'https://www.uni-stuttgart.de/en/','Allemand, Anglais',3,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (8,'Universidad Nacional de San Juan','AR-UNSJ','Argentine',NULL,'396 Este San Juan',-31.532970,-68.539549,'https://www.unsj.edu.ar/en/home','Espagnol',6,6,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (9,'Universidad Nacional de La Plata (UNLP)','AR-UNLP','Argentine',NULL,'Av. 7 Nº 776, La Plata (CP 1900), Buenos Aires',-34.913196,-57.950548,'https://unlp.edu.ar/','Espagnol',3,6,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (10,'Universidad Nacional de Cuyo','AR-UNDC','Argentine',NULL,'Centro Universitario, Ciudad de Mendoza, Provincia de Mendoza',-32.880579,-68.877117,'https://www.uncuyo.edu.ar/ingles','Espagnol',4,6,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (11,'Fachhochschule Technikum Wien','AT-FTW','Autriche',NULL,'Höchstädtplatz 6, 1200 Wien',48.239390,16.378161,'https://www.technikum-wien.at/en/','Allemand, Anglais',3,6,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (12,'Haute Ecole de la communauté française en Hainaut','BE-HECFH','Belgique',NULL,'4 rue Pierre-Joseph Dumènil, 7000 Mons',50.460011,3.957373,'https://www.heh.be/','Français',2,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (13,'Université de Liège','BE-UDL','Belgique',NULL,'Place du 20-Août, 7 - 4000 Liège',50.640963,5.576498,'https://www.uliege.be/cms/c_8699436/fr/uliege','Français',2,3,NULL,NULL,13.00,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (14,'Haute Ecole de la province de Liège','BE-HEPL','Belgique',NULL,'Quai des Carmes 45, 4101 Seraing',50.618732,5.515555,'https://www.hepl.be/fr','Français',5,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (15,'Universidade Federal Fluminense - DD','BR-UFF-DD','Brésil',NULL,'Reitoria da UFF – Rua Miguel de Frias, 9, Icaraí. Niterói',-22.902970,-43.115818,'https://www.uff.br/','Portugais',6,6,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (16,'Universidade Federal Fluminense','BR-UFF','Brésil',NULL,'Reitoria da UFF – Rua Miguel de Frias, 9, Icaraí. Niterói',-22.902970,-43.115818,'https://www.uff.br/','Portugais',6,6,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (17,'Universidade Federal de Viçosa','BR-UFV','Brésil',NULL,'Av. Peter Henry Rolfs, s/n, Campus Universitário, 36570-900 Viçosa/MG',-20.760833,-42.869774,'https://www.ufv.br/','Portugais',6,6,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (18,'Florianopolis : Universidade Federal de Santa Catarina','BR-UFSC','Brésil',NULL,'Campus Universitário Reitor João David Ferreira Lima Trindade – Florianópolis – SC',-27.323920,-48.038625,'https://en.ufsc.br/','Portugais',6,6,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (19,'Universidade Federal de Rio de Janeiro (UFRJ)','BR-UFRJ','Brésil',NULL,'Avenida Aluízio da Silva Gomes, 50 – Bairro da Glória, Macaé – RJ',-22.845187,-43.279214,'https://portal.macae.ufrj.br/en/instituto-politecnico-celebra-a-colacao-de-grau-oficial-dos-egressos-dos-cursos-de-engenharias/','Portugais',3,3,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (20,'Faculdade de Tecnologia Senai Cimatec','BR-FTSC','Brésil',NULL,'Av. Orlando Gomes, 1845 - Piatã, Salvador - BA',-12.938270,-38.386805,'https://www.senaicimatec.com.br/en/','Portugais',3,3,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (21,'Université de Sherbrooke - Faculté des Sciences - DD','CA-UDS-FS','Canada',NULL,'2500, boul. de l\'Université, Sherbrooke',45.381095,-71.926456,'https://www.usherbrooke.ca/sciences/','Français',0,5,NULL,NULL,12.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (22,'Université de Sherbrooke - Faculté de Génie - DD','CA-UDSF-FG','Canada',NULL,'2500, boul. de l\'Université, Sherbrooke',45.377998,-71.928870,'https://www.usherbrooke.ca/genie/','Français',0,6,NULL,NULL,12.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (23,'Université de Sherbrooke','CA-UDS','Canada',NULL,'2500, boul. de l\'Université, Sherbrooke',45.377998,-71.928870,'https://www.usherbrooke.ca/genie/','Français',0,9,NULL,NULL,11.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (24,'Université du Québec à Chicoutimi','CA-UQAC','Canada',NULL,'555, boulevard de l\'Université, Chicoutimi (Québec)',48.417825,-71.051436,'https://www.uqac.ca/','Français',0,1,NULL,NULL,11.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (25,'Université du Québec à Chicoutimi - DD','CA-UQAC-DD','Canada',NULL,'555, boulevard de l\'Université, Chicoutimi (Québec)',48.417825,-71.051436,'https://www.uqac.ca/','Français',0,6,NULL,NULL,12.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (26,'Ecole de Technologie Supérieure (ETS)','CA-ETS','Canada',NULL,'1100, rue Notre-Dame Ouest (angle Peel au sud), Montréal (Qc)',45.494944,-73.561854,'https://www.etsmtl.ca/','Français',0,3,NULL,NULL,11.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (27,'Ecole de Technologie Supérieure (ETS) - DD Maîtrise en sciences appliquées avec mémoire','CA-EDTS-DDM','Canada',NULL,'1100, rue Notre-Dame Ouest (angle Peel au sud), Montréal (Qc)',45.494944,-73.561854,'https://www.etsmtl.ca/','Français',0,5,NULL,NULL,12.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (28,'Ecole de Technologie Supérieure (ETS) - DD en ingénierie avec projet','CA-EDTS-DDP','Canada',NULL,'1100, rue Notre-Dame Ouest (angle Peel au sud), Montréal (Qc)',45.494944,-73.561854,'https://www.etsmtl.ca/','Français',0,5,NULL,NULL,12.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (29,'University of Seoul','CA-BCI','Corée du Sud',NULL,'163 Seoulsiripdaero, Dongdaemun-gu, Seoul',37.584044,127.059249,'https://www.uos.ac.kr/eng/web/main','Anglais',0,1,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (30,'Syddansk Universitet','KR-UOS','Danemark',NULL,'University of Southern Denmark, Campusvej 55 Odense',55.386755,10.369315,'https://www.sdu.dk/en','Anglais',2,3,NULL,NULL,12.00,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (31,'Escuela Tecnica Superior de Ingeniera Informatica/Universidad de Sevilla','DK-SU','Espagne',NULL,'Avda. Reina Mercedes s/n, 41012 Sevilla',37.358345,-5.988161,'https://www.informatica.us.es/','Espagnol, Anglais',4,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (32,'Escuela Tecnica Superior de Ingeniera (ETSI)/Universidad Sevilla','ES-ETSI','Espagne',NULL,'Camino de los Descubrimientos, s/n Isla de la Cartuja, 41092 Seville',37.358379,-5.986465,'https://etsi.us.es/','Espagnol',2,4,NULL,NULL,13.00,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (33,'Universidad Santiago de Compostela','ES-ETSI-02','Espagne',NULL,'Praza do Obradoiro, 0, 15705 Santiago de Compostela, A Coruña',42.879531,-8.544624,'https://www.usc.gal/gl','Espagnol',2,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (34,'Escuela Tecnica Superior de Ingenierios Informaticos - UPM','ES-USDC','Espagne',NULL,'Campus de Montegancedo, 28660 Boadilla del Monte (Madrid)',40.405173,-3.838843,'https://www.etsiinf.upm.es/','Espagnol',3,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (35,'Escuela Tecnica Superior de Edificacion - UPM','ES-ETSI-UPM','Espagne',NULL,'Avenida Juan de Herrera 6 Madrid',40.439155,-3.730743,'https://www.edificacion.upm.es/','Espagnol',3,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (36,'Escuela Tecnica Superior de Ingenieria de Sistemas Informaticos - UPM','ES-ETSE-UPM','Espagne',NULL,'Calle Alan Turing s/n (Ctra. de Valencia, Km. 7) 28031 - MADRID',40.390048,-3.627183,'https://www.etsisi.upm.es/','Espagnol',4,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (37,'E.T.S.I. Minas y Energia - UPM','ES-ETSISI-UPM','Espagne',NULL,'C/ Ríos Rosas nº 21. 28003. Madrid',40.442307,-3.699964,'https://minasyenergia.upm.es/','Espagnol',6,6,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (38,'Universidad Rey Juan Carlos','ES-ME-UPM','Espagne',NULL,'Pº de los Artilleros, 38 Vicalvaro Madrid',40.406247,-3.609939,'https://www.urjc.es/','Espagnol',5,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (39,'Universidad Rovira I Virgili','ES-URJC','Espagne',NULL,'Av. Catalunya 35 - Tarragona',41.123122,1.249467,'https://www.urv.cat/en/','Espagnol, Anglais',6,6,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (40,'Universidad de Vigo','ES-URIV','Espagne',NULL,'Campus Universitario 36310 Vigo (Pontevedra)',42.169753,-8.682621,'https://www.uvigo.gal/','Espagnol',2,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (41,'Universidad de Jaen','ES-UDV','Espagne',NULL,'Campus Las Lagunillas s/n. 23071 - Jaén',37.788572,-3.776519,'https://www.ujaen.es/','Espagnol, Anglais',3,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (42,'Barcelona East School of Engineering (EEBE)','ES-UDJ','Espagne',NULL,'Campus Diagonal Besòs, Edifici A (EEBE) Av. Eduard Maristany Barcelona',41.414504,2.216824,'https://eebe.upc.edu/en/incoming','Espagnol',0,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (43,'Universidad Zaragoza','ES-BESE','Espagne',NULL,'Pedro Cerbuna, 12 - 50009 Zaragoza',41.642208,-0.900788,'https://www.unizar.es/','Espagnol',3,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (44,'Universidad Publica de Navarra','ES-UZ','Espagne',NULL,'Arrosadia, s/n 31006 Pamplona',42.800852,-1.636007,'https://www.unavarra.es/home','Espagnol',2,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (45,'Tallinn University of Technology','ES-UPDN','Estonie',NULL,'Ehitajate tee 5, 19086 Tallinn',59.394971,24.672358,'https://taltech.ee/en/','Anglais',4,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (46,'Universidad Nacional de Colombia','EE-TUOT','Colombie',NULL,'Ave Cra 30 #45-3, Bogotá, Colombie',4.636586,-74.082693,'https://unal.edu.co/','Espagnol',0,1,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (47,'Programme ISEP (Etats-Unis + Australie, Canada, Iles Fidji, Nouvelle-Zélande, Royaume-Uni)','CO-UNDC','Etats-Unis',NULL,'1655 N. Fort Myer Drive, Suite 400, Arlington, Virginia',38.894098,-77.071023,'https://www.isepstudyabroad.org/','Anglais',0,3,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (48,'Université du Nouveau-Mexique','US-ISEP','Etats-Unis',NULL,'The University of New Mexico, Albuquerque, NM 87131',35.090561,-106.618970,'https://engineering.unm.edu/','Anglais',0,1,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (49,'University of Technology Lappeenranta','US-UDNM','Finlande',NULL,'Yliopistonkatu 34 53850 Lappeenranta',61.065090,28.095143,'https://www.lut.fi/en','Anglais',1,2,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (50,'International Hellenic University','FI-UOTL','Grèce',NULL,'14th km Thessaloniki – N. Moudania - 57001 Thermi, Thessaloniki',40.537275,23.023301,'https://www.ihu.gr/ucips/','Anglais',0,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (51,'Technical University of Crete (TUC)','GR-IHU','Grèce',NULL,'University Campus, Akrotiri Chania 73100',35.529414,24.069378,'https://www.tuc.gr/en/home','Anglais',4,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (52,'University of West Attica','GR-TUOC','Grèce',NULL,'196 Alexandras Avenue, 11521 Athens',38.003639,23.674631,'https://www.uniwa.gr/en/','Anglais',0,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (53,'Universita degli studi di Brescia','GR-UOWA','Italie',NULL,'Piazza del Mercato, 15 - 25121 Brescia',45.538017,10.218177,'https://www.unibs.it/en','Italien, Anglais',5,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (54,'Universita degli studi di Modena & Reggio Emilia','IT-UDSD','Italie',NULL,'Via Università 4, 41121 Modena',44.645282,10.928982,'https://www.unimore.it/en','Italien, Anglais',3,5,NULL,NULL,13.00,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (55,'Universita degli studi di Genova','IT-UDSM','Italie',NULL,'Via Balbi 5, 16126 Genova',44.414941,8.927287,'https://unige.it/en','Italien, Anglais',1,6,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (56,'Universita degli studi di Genova - DD Master Solar','IT-UDSG-03','Italie',NULL,'Via Balbi 5, 16126 Genova',44.414941,8.927287,'https://unige.it/en','Italien, Anglais',0,6,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (57,'Universita degli studi di Genova - DD Master AM','IT-UDSG-ESBC','Italie',NULL,'Via Balbi 5, 16126 Genova',44.414941,8.927287,'https://unige.it/en','Italien, Anglais',0,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (58,'Universita degli studi di Trento','IT-UDSG-AM','Italie',NULL,'via Calepina, 14 - I-38122 Trento',46.067061,11.123163,'https://www.unitn.it/en','Italien, Anglais',1,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (59,'Universita di Torino','IT-UDST','Italie',NULL,'Via Verdi, 8 - 10124 Turin',45.069789,7.689803,'https://en.unito.it/','Italien, Anglais',3,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (60,'Kagawa University','IT-UDT','Japon',NULL,'Saiwaicho 1-1, Takamatsu City, Kagawa Prefecture 760-8521',34.342387,134.037012,'https://www.kagawa-u.ac.jp/en/','Japonais',1,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (61,'University of Hyogo','JP-KU','Japon',NULL,'8-2-1, Gakuennishi-machi, Nishi-ku, Kobe, Hyogo',34.748984,134.894925,'https://www.u-hyogo.ac.jp/english/','Japonais',1,1,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (62,'Ecole Nationale Supérieure des Mines de Rabat (ENSMR)','JP-UOH','Maroc',NULL,'Avenue Hadj Ahmed Cherkaoui BP 753 Agdal Rabat',33.998651,-6.855839,'https://www.enim.ac.ma/','Français',2,2,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (63,'Ecole Nationale Supérieur des Mines de Rabat (ENSMR) - DD','MA-ENSMR','Maroc',NULL,'Avenue Hadj Ahmed Cherkaoui BP 753 Agdal Rabat',33.998651,-6.855839,'https://www.enim.ac.ma/','Français',0,2,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (64,'Université Sultan Moulay Slimane','MA-ENSMR-DD','Maroc',NULL,'Mghila, 23000 Béni Mellal',32.336031,-6.368544,'https://ensabm.usms.ac.ma/','Français',5,5,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (65,'Ecole Nationale des Sciences Appliquées d\'El Jadida','MA-USMS','Maroc',NULL,'Route d\'Azemmour, Nationale N°1, ELHAOUZIA 5096 El Jadida',33.252539,-8.432919,'https://www.ensaj.ucd.ac.ma/','Français',3,3,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (66,'Instituto Tecnologico de Querétaro','MX-ITDQ','Mexique',NULL,'Av Tecnologico S/N, centro historico, centro 76000 Santiago de Querétaro',20.593539,-100.405025,'https://queretaro.tecnm.mx/','Espagnol',3,3,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (67,'Universidad Autonoma de Querétaro','MX-UADQ','Mexique',NULL,'Universidad 231, cerro de las campanas S/N, las campanas',20.592117,-100.409776,'https://www.uaq.mx/','Espagnol',3,3,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (68,'Norges Teknisk-Naturvitenskaplige Universitet (NTNU)','NO-NTNU','Norvège',NULL,'Postboks 8900, Torgarden, NO-7491 Trondheim',63.846598,12.026138,'https://www.ntnu.edu/','Anglais',0,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (69,'Hoyskolen Kristiania','NO-HK','Norvège',NULL,'Kirkegata 24-26, 0153 Oslo',59.911298,10.745541,'https://www.kristiania.no/en/','Anglais',0,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (70,'AGH University of Science and Technology','PL-AUOST','Pologne',NULL,'al. Adama Mickiewicza 30 Krakow',50.064634,19.923865,'https://www.agh.edu.pl/en','Anglais',1,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (71,'Universidade De Tras-os-Montes e Alto Douro','PT-UDTMAD','Portugal',NULL,'Quinta de Prados 5000-801 Vila Real',41.288701,-7.738599,'https://www.utad.pt/','Portugais',3,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (72,'Politechnico da Guarda','PT-PDG','Portugal',NULL,'Avenida Dr. Francisco Sá Carneiro, n.º 50 6300-559 Guarda',40.539187,-7.279400,'https://politecnicoguarda.pt/en/homepage/','Portugais',5,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (73,'Universidade de Beira Interior','PT-UDBI','Portugal',NULL,'R. Marques de Avila e Bolama 6201-001 Covilha',40.277998,-7.508522,'https://www.ubi.pt/en/','Portugais',4,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (74,'Technicka Univerzita v Liberci','CZ-TUVL','République Tchèque',NULL,'Studentská 1402/2 - 461 17 Liberec 1',50.773266,15.074454,'https://www.tul.cz/en/home-page/','Anglais',3,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (75,'Université Technique Prague','CZ-UTP','République Tchèque',NULL,'Jugoslavskych Partyzanu 1508/3 1600 00 Prague 6',50.103354,14.394783,'https://www.cvut.cz/en','Anglais',0,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (76,'Ecole Supérieure d\'Ingénieurs Réunion Océan Indien','FR-REU-ESIROI','Réunion',NULL,'40, avenue de Soweto - BP 373 97455 Saint-Pierre CEDEX',-21.340256,55.491733,'https://esiroi.univ-reunion.fr/','Français',0,3,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (77,'Universitatea Politehnica din Bucuresti','RO-UPDB','Roumanie',NULL,'Splaiul Independenceei no. 313, sector 6, Bucharest, ROMANIA',44.438714,26.050233,'https://upb.ro/en/','Français, Anglais',4,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (78,'Universitatea Tehnica de Constructii Bucuresti','RO-UTDCB','Roumanie',NULL,'Bd. Lacul Tei nr. 122 - 124, cod 020396, Sector 2, Bucuresti',44.463270,26.125995,'https://utcb.ro/','Français, Anglais',1,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (79,'Universitatea de Vest din Timisoara','RO-UDVDT','Roumanie',NULL,'Bd. Vasile Pârvan no. 4, Timișoara, postal code 300223, Timił county',45.747247,21.232259,'https://www.uvt.ro/en/','Français, Anglais',1,2,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (80,'Universitatea Babes-Bolyai','RO-UBB','Roumanie',NULL,'68, Avram Iancu Street, RO-400083, Cluj-Napoca, Cluj, Romania',46.767258,23.592826,'https://cci.ubbcluj.ro/','Français, Anglais',6,6,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (81,'Universitatea Transilvania din Brasov','RO-UTDB','Roumanie',NULL,'B-dul Eroilor nr. 29, Cod postal 500036, Brașov, România',45.645461,25.589902,'https://www.unitbv.ro/en/','Français, Anglais',5,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (82,'Université Cheikh Anta Diop','SN-UCAD','Sénégal',NULL,'Corniche Ouest BP : 5085 Dakar-Fann',14.690803,-17.458868,'https://esp.sn/','Français',0,0,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (83,'Université Gaston Berger','SN-UGB','Sénégal',NULL,'Saint Louis Sénégal',16.061780,-16.421211,'https://www.ugb.sn/','Français',0,0,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (84,'Slovenska Technicka Univerzita v Bratislave','SK-STUVB','Slovaquie',NULL,'Vazovova 5, 812 43 Bratislava 1, Slovak Republic',48.154729,17.117872,'https://www.stuba.sk/','Anglais',3,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (85,'University of Ljubljana','SI-UOL','Slovénie',NULL,'Aškerčeva cesta 6 1000 Ljubljana',46.047493,14.498981,'https://www.fs.uni-lj.si/en/','Anglais',3,4,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (86,'University of technology Luleå','SE-UOTL','Suède',NULL,'97187 Luleå, Sweden',65.618067,22.140126,'https://www.ltu.se/en','Anglais',1,3,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (87,'Högskolan I Borås','SE-HB','Suède',NULL,'S-501 90 Borås',57.725248,12.939822,'https://www.hb.se/en/','Anglais',4,6,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (88,'Högskolan Dalarna','SE-HD','Suède',NULL,'Stationsgatan 4, Borlänge',60.485399,15.432667,'https://www.du.se/en','Anglais',5,5,NULL,NULL,NULL,'ERASMUS',NULL);
INSERT INTO `MOB_partner_university` VALUES (89,'BFH Bern University of Applied Sciences','CH-BUAS','Suisse',NULL,'Bern Holzikofenweg 8',46.937107,7.433990,'https://www.bfh.ch/ahb/fr/','Anglais, Allemand',0,0,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (90,'National United University (NUU)','TW-NUU','Taïwan',NULL,'No.1, Lienda, Miaoli 360301, Taiwan',24.546052,120.812880,'https://www.nuu.edu.tw/index.php?Lang=en','Anglais',3,3,NULL,NULL,NULL,'Bilateral',NULL);
INSERT INTO `MOB_partner_university` VALUES (91,'Polytech Annecy-Chambery','MOB_STAGE','France',NULL,'5 chemin de Bellevue, 74940 Annecy-le-Vieux',45.919731,6.157739,NULL,'francais',NULL,NULL,NULL,NULL,NULL,'stage',NULL);
/*!40000 ALTER TABLE `MOB_partner_university` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MOB_partner_university_places` WRITE;
/*!40000 ALTER TABLE `MOB_partner_university_places` DISABLE KEYS */;
/*!40000 ALTER TABLE `MOB_partner_university_places` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `MOB_wishes` WRITE;
/*!40000 ALTER TABLE `MOB_wishes` DISABLE KEYS */;
/*!40000 ALTER TABLE `MOB_wishes` ENABLE KEYS */;
UNLOCK TABLES;